In [0]:
import pandas as pd
import numpy as np
import zipfile

In [21]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
zip_ref = zipfile.ZipFile("/content/drive/My Drive/ML Project/YouTube-Spam-Collection-v1.zip", 'r')
zip_ref.extractall()
zip_ref.close()

In [23]:
df=pd.read_csv('/content/Youtube02-KatyPerry.csv')
df.head()

COMMENT_ID  ... CLASS
0      z12pgdhovmrktzm3i23es5d5junftft3f  ...     1
1    z13yx345uxepetggz04ci5rjcxeohzlrtf4  ...     1
2  z12lsjvi3wa5x1vwh04cibeaqnzrevxajw00k  ...     1
3    z13jcjuovxbwfr0ge04cev2ipsjdfdurwck  ...     1
4  z13qybua2yfydzxzj04cgfpqdt2syfx53ms0k  ...     1

[5 rows x 5 columns]

In [24]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [25]:
df=df[['CONTENT','CLASS']] #for selecting only class and content columns
df.head()

CONTENT  CLASS
0  i love this so much. AND also I Generate Free ...      1
1  http://www.billboard.com/articles/columns/pop-...      1
2  Hey guys! Please join me in my fight to help a...      1
3  http://psnboss.com/?ref=2tGgp3pV6L this is the...      1
4  Hey everyone. Watch this trailer!!!!!!!!  http...      1

In [0]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer #keeps only single word out of many having same meaning
ps = PorterStemmer()

In [27]:
corpus=[]
import re
for i in range(0,df.shape[0]):
    x = re.sub('[^a-zA-Z]', ' ',df['CONTENT'].iloc[i])
    x = x.split()
    x = [ps.stem(word) for word in x if not word in set(stopwords.words('english'))]
    x = ' '.join(x)
    corpus.append(x)
corpus

['love much and also I gener free lead auto pilot amp you can too http www myleaderg com moretraff',
 'http www billboard com articl column pop shop fan armi face round vote sone pleas vip pleas help us gt lt',
 'hey guy pleas join fight help abus mistreat anim all fund go help pay vet bill help find home I place extra emphasi help disabl anim one otherwis would put sleep anim organ donat pleas http www gofundm com angel n wingz',
 'http psnboss com ref tggp pV L song',
 'hey everyon watch trailer http believemefilm com hlr h hqbuvb',
 'check rap hope guy like http soundcloud com nereboy call lostproduc atlastatla rapper jkork follow messag',
 'subscrib pleaaaas instagram account subscrib back http instagram com cyrin ghorbel',
 'hey guy visit channel pleaas search dream',
 'nice http www barnesandnobl com bdp csrftoken I tix cnkcosoqkemgjlu uwv nsxso amp sort DD amp size amp csrftoken iyec nrwp nytno U amhvmflutggl amp dref amp keyword bdp amp store ebook',
 'http www twitch tv daconn

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer() #counts frequency of word in a sentence (here corpus)
x = cv.fit_transform(corpus).toarray()
#from sklearn.feature_extraction.text import TfidfVectorizer
#vectorizer = TfidfVectorizer()
#x = vectorizer.fit_transform(corpus).toarray()

In [29]:
x #for input

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [30]:
x.shape

(350, 1531)

In [0]:
y = df['CLASS'].values #for output


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3,random_state=0)

LogisticRegression(LR)


In [33]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred = classifier.predict(X_test)

In [35]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[51  0]
 [ 5 49]]
Classification accuracy = 95.23809523809523 %

              precision    recall  f1-score   support

           0       0.91      1.00      0.95        51
           1       1.00      0.91      0.95        54

    accuracy                           0.95       105
   macro avg       0.96      0.95      0.95       105
weighted avg       0.96      0.95      0.95       105



In [36]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.9090593428863096

Random Forest(RF)

In [37]:
from sklearn.ensemble import RandomForestClassifier
clfRF = RandomForestClassifier(max_depth=2, random_state=0)
clfRF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred=clfRF.predict(X_test)

In [39]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[51  0]
 [12 42]]
Classification accuracy = 88.57142857142857 %

              precision    recall  f1-score   support

           0       0.81      1.00      0.89        51
           1       1.00      0.78      0.88        54

    accuracy                           0.89       105
   macro avg       0.90      0.89      0.88       105
weighted avg       0.91      0.89      0.88       105



In [40]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7934920476158722

DecisionTree(CART)


In [41]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [0]:
y_pred = classifier.predict(X_test)

In [43]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[49  2]
 [ 8 46]]
Classification accuracy = 90.47619047619048 %

              precision    recall  f1-score   support

           0       0.86      0.96      0.91        51
           1       0.96      0.85      0.90        54

    accuracy                           0.90       105
   macro avg       0.91      0.91      0.90       105
weighted avg       0.91      0.90      0.90       105



In [44]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8153049286416899

K-Nearest neighbors(KNN)(3-NN)


In [45]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh.predict(X_test)

In [47]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[50  1]
 [11 43]]
Classification accuracy = 88.57142857142857 %

              precision    recall  f1-score   support

           0       0.82      0.98      0.89        51
           1       0.98      0.80      0.88        54

    accuracy                           0.89       105
   macro avg       0.90      0.89      0.89       105
weighted avg       0.90      0.89      0.88       105



In [48]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7867514660548713

K-Nearest neighbors(KNN)(1-NN)

In [49]:
from sklearn.neighbors import KNeighborsClassifier
neigh1 = KNeighborsClassifier(n_neighbors=1)
neigh1.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh1.predict(X_test)

In [51]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[50  1]
 [ 9 45]]
Classification accuracy = 90.47619047619048 %

              precision    recall  f1-score   support

           0       0.85      0.98      0.91        51
           1       0.98      0.83      0.90        54

    accuracy                           0.90       105
   macro avg       0.91      0.91      0.90       105
weighted avg       0.91      0.90      0.90       105



In [52]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8197000600695623

K-Nearest neighbors(KNN)(5-NN)

In [53]:
from sklearn.neighbors import KNeighborsClassifier
neigh5 = KNeighborsClassifier(n_neighbors=5)
neigh5.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh5.predict(X_test)

In [55]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[50  1]
 [16 38]]
Classification accuracy = 83.80952380952381 %

              precision    recall  f1-score   support

           0       0.76      0.98      0.85        51
           1       0.97      0.70      0.82        54

    accuracy                           0.84       105
   macro avg       0.87      0.84      0.84       105
weighted avg       0.87      0.84      0.84       105



In [56]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7076111363746075

Support Vector Machine with Linear Kernel(SVM-L)

In [57]:
from sklearn import svm
svc = svm.SVC(kernel ='linear', C = 1)
svc.fit(X_train, y_train) 

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svc.predict(X_test)

In [59]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[50  1]
 [ 3 51]]
Classification accuracy = 96.19047619047619 %

              precision    recall  f1-score   support

           0       0.94      0.98      0.96        51
           1       0.98      0.94      0.96        54

    accuracy                           0.96       105
   macro avg       0.96      0.96      0.96       105
weighted avg       0.96      0.96      0.96       105



In [60]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.9245009683433849

Support Vector Machine with Polynomial Kernel(SVM-P)

In [61]:
from sklearn import svm
svcpoly= svm.SVC(kernel='poly',gamma=2)
svcpoly.fit(X_train, y_train) 

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=2, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svcpoly.predict(X_test)

In [63]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[50  1]
 [15 39]]
Classification accuracy = 84.76190476190476 %

              precision    recall  f1-score   support

           0       0.77      0.98      0.86        51
           1       0.97      0.72      0.83        54

    accuracy                           0.85       105
   macro avg       0.87      0.85      0.85       105
weighted avg       0.88      0.85      0.85       105



In [64]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7231232535460359

Support Vector Machine with Gaussian Kernel(SVM-R)

In [65]:
from sklearn import svm
svcrbf= svm.SVC(kernel='rbf')
svcrbf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svcrbf.predict(X_test)

In [67]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[49  2]
 [ 5 49]]
Classification accuracy = 93.33333333333333 %

              precision    recall  f1-score   support

           0       0.91      0.96      0.93        51
           1       0.96      0.91      0.93        54

    accuracy                           0.93       105
   macro avg       0.93      0.93      0.93       105
weighted avg       0.93      0.93      0.93       105



In [68]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8681917211328976

Bernoulli Naive Bayes(NB-B)

In [69]:
from sklearn.naive_bayes import BernoulliNB
clfBNB = BernoulliNB()
clfBNB.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [0]:
y_pred=clfBNB.predict(X_test)

In [71]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[51  0]
 [21 33]]
Classification accuracy = 80.0 %

              precision    recall  f1-score   support

           0       0.71      1.00      0.83        51
           1       1.00      0.61      0.76        54

    accuracy                           0.80       105
   macro avg       0.85      0.81      0.79       105
weighted avg       0.86      0.80      0.79       105



In [72]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.6579288490181673

Multinomial Naive Bayes(NB-M)


In [73]:
from sklearn.naive_bayes import MultinomialNB
clfMNB = MultinomialNB()
clfMNB.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
y_pred=clfMNB.predict(X_test)

In [75]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[48  3]
 [ 6 48]]
Classification accuracy = 91.42857142857143 %

              precision    recall  f1-score   support

           0       0.89      0.94      0.91        51
           1       0.94      0.89      0.91        54

    accuracy                           0.91       105
   macro avg       0.92      0.92      0.91       105
weighted avg       0.92      0.91      0.91       105



In [76]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8300653594771242

Gaussian Naive Bayes(NB-G)

In [77]:
from sklearn.naive_bayes import GaussianNB
clfGNB = GaussianNB()
clfGNB.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred=clfGNB.predict(X_test)

In [79]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[40 11]
 [ 6 48]]
Classification accuracy = 83.80952380952381 %

              precision    recall  f1-score   support

           0       0.87      0.78      0.82        51
           1       0.81      0.89      0.85        54

    accuracy                           0.84       105
   macro avg       0.84      0.84      0.84       105
weighted avg       0.84      0.84      0.84       105



In [80]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.6781454312222082