In [0]:
import pandas as pd
import numpy as np
import zipfile

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
zip_ref = zipfile.ZipFile("/content/drive/My Drive/ML Project/YouTube-Spam-Collection-v1.zip", 'r')
zip_ref.extractall()
zip_ref.close()

In [6]:
df=pd.read_csv('/content/Youtube04-Eminem.csv')
df.head()

COMMENT_ID  ... CLASS
0    z12rwfnyyrbsefonb232i5ehdxzkjzjs2  ...     1
1  z130wpnwwnyuetxcn23xf5k5ynmkdpjrj04  ...     0
2    z13vsfqirtavjvu0t22ezrgzyorwxhpf3  ...     1
3  z12wjzc4eprnvja4304cgbbizuved35wxcs  ...     0
4    z13xjfr42z3uxdz2223gx5rrzs3dt5hna  ...     1

[5 rows x 5 columns]

In [7]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [8]:
df=df[['CONTENT','CLASS']]
df.head()

CONTENT  CLASS
0          +447935454150 lovely girl talk to me xxx      1
1    I always end up coming back to this song<br />      0
2  my sister just received over 6,500 new <a rel=...      1
3                                              Cool      0
4                     Hello I&#39;am from Palastine      1

In [0]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [10]:
corpus=[]
import re
for i in range(0,df.shape[0]):
    x = re.sub('[^a-zA-Z]', ' ',df['CONTENT'].iloc[i])
    x = x.split()
    x = [ps.stem(word) for word in x if not word in set(stopwords.words('english'))]
    x = ' '.join(x)
    corpus.append(x)
corpus

['love girl talk xxx',
 'I alway end come back song br',
 'sister receiv new rel nofollow class ot hashtag href http plu googl com activ activ youtub view right the thing use pimpmyview com',
 'cool',
 'hello I palastin',
 'wow video almost billion view didn know popular',
 'Go check rap video call four wheel pleas',
 'almost billion',
 'aslamu lykum from pakistan',
 'eminem idol peopl espa mexico latinoamerica',
 'help get sub pleas',
 'love song',
 'alright ladi like song check john rage He smoke hot rapper come game He better eminem lyric hotter hear song channel',
 'the perfect exampl abus husband thing I feminist I definit agre song well I see someon go die just sayin',
 'the boyfriend charli TV show lost',
 'href http www facebook com group http www facebook com group',
 'take look video youtub',
 'check channel nice beat',
 'rihanna eminem togeth unstopp',
 'check playlist youtub',
 'thi song rape cheat br br br br br br br br br br basic',
 'like pleas',
 'I love song believ ye

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()

In [12]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
x.shape

(448, 1341)

In [0]:
y = df['CLASS'].values


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3,random_state=35)

LogisticRegression(LR)


In [16]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred = classifier.predict(X_test)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[64  1]
 [ 5 65]]
Classification accuracy = 95.55555555555556 %

              precision    recall  f1-score   support

           0       0.93      0.98      0.96        65
           1       0.98      0.93      0.96        70

    accuracy                           0.96       135
   macro avg       0.96      0.96      0.96       135
weighted avg       0.96      0.96      0.96       135



In [19]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.9127856768559333

Random Forest(RF)

In [20]:
from sklearn.ensemble import RandomForestClassifier
clfRF = RandomForestClassifier(max_depth=2, random_state=0)
clfRF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred=clfRF.predict(X_test)

In [22]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[46 19]
 [ 0 70]]
Classification accuracy = 85.92592592592592 %

              precision    recall  f1-score   support

           0       1.00      0.71      0.83        65
           1       0.79      1.00      0.88        70

    accuracy                           0.86       135
   macro avg       0.89      0.85      0.85       135
weighted avg       0.89      0.86      0.86       135



In [23]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7460642917325853

DecisionTree(CART)


In [24]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [0]:
y_pred = classifier.predict(X_test)

In [26]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[64  1]
 [ 3 67]]
Classification accuracy = 97.03703703703704 %

              precision    recall  f1-score   support

           0       0.96      0.98      0.97        65
           1       0.99      0.96      0.97        70

    accuracy                           0.97       135
   macro avg       0.97      0.97      0.97       135
weighted avg       0.97      0.97      0.97       135



In [27]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.9411379157000955

K-Nearest neighbors(KNN)(3-NN)


In [28]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh.predict(X_test)

In [30]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[65  0]
 [18 52]]
Classification accuracy = 86.66666666666667 %

              precision    recall  f1-score   support

           0       0.78      1.00      0.88        65
           1       1.00      0.74      0.85        70

    accuracy                           0.87       135
   macro avg       0.89      0.87      0.87       135
weighted avg       0.90      0.87      0.86       135



In [31]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7627290435035148

K-Nearest neighbors(KNN)(1-NN)

In [32]:
from sklearn.neighbors import KNeighborsClassifier
neigh1 = KNeighborsClassifier(n_neighbors=1)
neigh1.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh1.predict(X_test)

In [34]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[64  1]
 [19 51]]
Classification accuracy = 85.18518518518519 %

              precision    recall  f1-score   support

           0       0.77      0.98      0.86        65
           1       0.98      0.73      0.84        70

    accuracy                           0.85       135
   macro avg       0.88      0.86      0.85       135
weighted avg       0.88      0.85      0.85       135



In [35]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7322650136594395

K-Nearest neighbors(KNN)(5-NN)

In [36]:
from sklearn.neighbors import KNeighborsClassifier
neigh5 = KNeighborsClassifier(n_neighbors=5)
neigh5.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh5.predict(X_test)

In [38]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[65  0]
 [23 47]]
Classification accuracy = 82.96296296296296 %

              precision    recall  f1-score   support

           0       0.74      1.00      0.85        65
           1       1.00      0.67      0.80        70

    accuracy                           0.83       135
   macro avg       0.87      0.84      0.83       135
weighted avg       0.87      0.83      0.83       135



In [39]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.704231182525709

Support Vector Machine with Linear Kernel(SVM-L)

In [40]:
from sklearn import svm
svc = svm.SVC(kernel ='linear', C = 1)
svc.fit(X_train, y_train) 

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svc.predict(X_test)

In [42]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))


[[64  1]
 [ 4 66]]
Classification accuracy = 96.29629629629629 %

              precision    recall  f1-score   support

           0       0.94      0.98      0.96        65
           1       0.99      0.94      0.96        70

    accuracy                           0.96       135
   macro avg       0.96      0.96      0.96       135
weighted avg       0.96      0.96      0.96       135



In [43]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.9268616112612377

Support Vector Machine with Polynomial Kernel(SVM-P)

In [44]:
from sklearn import svm
svcpoly= svm.SVC(kernel='poly',gamma=2)
svcpoly.fit(X_train, y_train) 

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=2, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svcpoly.predict(X_test)

In [46]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[65  0]
 [20 50]]
Classification accuracy = 85.18518518518519 %

              precision    recall  f1-score   support

           0       0.76      1.00      0.87        65
           1       1.00      0.71      0.83        70

    accuracy                           0.85       135
   macro avg       0.88      0.86      0.85       135
weighted avg       0.89      0.85      0.85       135



In [47]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7390659560519331

Support Vector Machine with Gaussian Kernel(SVM-R)

In [48]:
from sklearn import svm
svcrbf= svm.SVC(kernel='rbf')
svcrbf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svcrbf.predict(X_test)

In [50]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[63  2]
 [ 4 66]]
Classification accuracy = 95.55555555555556 %

              precision    recall  f1-score   support

           0       0.94      0.97      0.95        65
           1       0.97      0.94      0.96        70

    accuracy                           0.96       135
   macro avg       0.96      0.96      0.96       135
weighted avg       0.96      0.96      0.96       135



In [51]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.9114871295578522

Bernoulli Naive Bayes(NB-B)

In [52]:
from sklearn.naive_bayes import BernoulliNB
clfBNB = BernoulliNB()
clfBNB.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [0]:
y_pred=clfBNB.predict(X_test)

In [54]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[64  1]
 [17 53]]
Classification accuracy = 86.66666666666667 %

              precision    recall  f1-score   support

           0       0.79      0.98      0.88        65
           1       0.98      0.76      0.85        70

    accuracy                           0.87       135
   macro avg       0.89      0.87      0.87       135
weighted avg       0.89      0.87      0.87       135



In [55]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.756534415836003

Multinomial Naive Bayes(NB-M)


In [56]:
from sklearn.naive_bayes import MultinomialNB
clfMNB = MultinomialNB()
clfMNB.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
y_pred=clfMNB.predict(X_test)

In [58]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[51 14]
 [ 7 63]]
Classification accuracy = 84.44444444444444 %

              precision    recall  f1-score   support

           0       0.88      0.78      0.83        65
           1       0.82      0.90      0.86        70

    accuracy                           0.84       135
   macro avg       0.85      0.84      0.84       135
weighted avg       0.85      0.84      0.84       135



In [59]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.6910237806652532

Gaussian Naive Bayes(NB-G)

In [60]:
from sklearn.naive_bayes import GaussianNB
clfGNB = GaussianNB()
clfGNB.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred=clfGNB.predict(X_test)

In [62]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[41 24]
 [ 1 69]]
Classification accuracy = 81.48148148148148 %

              precision    recall  f1-score   support

           0       0.98      0.63      0.77        65
           1       0.74      0.99      0.85        70

    accuracy                           0.81       135
   macro avg       0.86      0.81      0.81       135
weighted avg       0.85      0.81      0.81       135



In [63]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.6653666787094018