In [0]:
import pandas as pd
import numpy as np
import zipfile

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
zip_ref = zipfile.ZipFile("/content/drive/My Drive/ML Project/YouTube-Spam-Collection-v1.zip", 'r')
zip_ref.extractall()
zip_ref.close()

In [5]:
df=pd.read_csv('/content/Youtube05-Shakira.csv')
df.head()

COMMENT_ID  ... CLASS
0    z13lgffb5w3ddx1ul22qy1wxspy5cpkz504  ...     0
1      z123dbgb0mqjfxbtz22ucjc5jvzcv3ykj  ...     0
2  z12quxxp2vutflkxv04cihggzt2azl34pms0k  ...     0
3      z12icv3ysqvlwth2c23eddlykyqut5z1h  ...     0
4      z133stly3kete3tly22petvwdpmghrlli  ...     0

[5 rows x 5 columns]

In [6]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [7]:
df=df[['CONTENT','CLASS']]
df.head()

CONTENT  CLASS
0                                         Nice song      0
1                                      I love song       0
2                                      I love song       0
3  860,000,000 lets make it first female to reach...      0
4                      shakira is best for worldcup      0

In [0]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [9]:
corpus=[]
import re
for i in range(0,df.shape[0]):
    x = re.sub('[^a-zA-Z]', ' ',df['CONTENT'].iloc[i])
    x = x.split()
    x = [ps.stem(word) for word in x if not word in set(stopwords.words('english'))]
    x = ' '.join(x)
    corpus.append(x)
corpus

['nice song',
 'I love song',
 'I love song',
 'let make first femal reach one billion share replay',
 'shakira best worldcup',
 'the best world cup song ever',
 'I love',
 'see some more song open googl and type shakira guruofmovi',
 'awesom',
 'I like shakira',
 'shakira waka waka br love thi song',
 'whi mani dislik',
 'I think song ever get old',
 'love song',
 'weri good',
 'everi time I hear song I think iniesta goal netherland',
 'whose watch If hi',
 'I love song much lt br keep em come',
 'love song thumsb',
 'waka best one',
 'year later still love song br axi',
 'like',
 'check playlist youtub',
 'her voic sound weird plu cute blond',
 'whi mani dislik thi song awesom It sound like must stop BE racist If I could I would like time',
 'nice love itttttttt wurkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
 'still watch',
 'shakira favourit singer wooooo',
 'rememb song',
 'like',
 'whose watch like',
 'support fight th am

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()

In [11]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
x.shape

(370, 1100)

In [0]:
y = df['CLASS'].values


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25,random_state=42)

LogisticRegression(LR)


In [15]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred = classifier.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[49  1]
 [ 3 40]]
Classification accuracy = 95.6989247311828 %

              precision    recall  f1-score   support

           0       0.94      0.98      0.96        50
           1       0.98      0.93      0.95        43

    accuracy                           0.96        93
   macro avg       0.96      0.96      0.96        93
weighted avg       0.96      0.96      0.96        93



In [18]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.914066927102621

Random Forest(RF)

In [19]:
from sklearn.ensemble import RandomForestClassifier
clfRF = RandomForestClassifier(max_depth=2, random_state=0)
clfRF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred=clfRF.predict(X_test)

In [21]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[50  0]
 [15 28]]
Classification accuracy = 83.87096774193549 %

              precision    recall  f1-score   support

           0       0.77      1.00      0.87        50
           1       1.00      0.65      0.79        43

    accuracy                           0.84        93
   macro avg       0.88      0.83      0.83        93
weighted avg       0.88      0.84      0.83        93



In [22]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7077389733389186

DecisionTree(CART)


In [23]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [0]:
y_pred = classifier.predict(X_test)

In [25]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[49  1]
 [ 4 39]]
Classification accuracy = 94.6236559139785 %

              precision    recall  f1-score   support

           0       0.92      0.98      0.95        50
           1       0.97      0.91      0.94        43

    accuracy                           0.95        93
   macro avg       0.95      0.94      0.95        93
weighted avg       0.95      0.95      0.95        93



In [26]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8932304767028219

K-Nearest neighbors(KNN)(3-NN)


In [27]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh.predict(X_test)

In [29]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[49  1]
 [10 33]]
Classification accuracy = 88.17204301075269 %

              precision    recall  f1-score   support

           0       0.83      0.98      0.90        50
           1       0.97      0.77      0.86        43

    accuracy                           0.88        93
   macro avg       0.90      0.87      0.88        93
weighted avg       0.90      0.88      0.88        93



In [30]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7738043778875944

K-Nearest neighbors(KNN)(1-NN)

In [31]:
from sklearn.neighbors import KNeighborsClassifier
neigh1 = KNeighborsClassifier(n_neighbors=1)
neigh1.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh1.predict(X_test)

In [33]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[44  6]
 [ 8 35]]
Classification accuracy = 84.94623655913979 %

              precision    recall  f1-score   support

           0       0.85      0.88      0.86        50
           1       0.85      0.81      0.83        43

    accuracy                           0.85        93
   macro avg       0.85      0.85      0.85        93
weighted avg       0.85      0.85      0.85        93



In [34]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.696876778353148

K-Nearest neighbors(KNN)(5-NN)

In [35]:
from sklearn.neighbors import KNeighborsClassifier
neigh5 = KNeighborsClassifier(n_neighbors=5)
neigh5.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh5.predict(X_test)

In [37]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[50  0]
 [12 31]]
Classification accuracy = 87.09677419354838 %

              precision    recall  f1-score   support

           0       0.81      1.00      0.89        50
           1       1.00      0.72      0.84        43

    accuracy                           0.87        93
   macro avg       0.90      0.86      0.87        93
weighted avg       0.90      0.87      0.87        93



In [38]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7624928516630233

Support Vector Machine with Linear Kernel(SVM-L)

In [39]:
from sklearn import svm
svc = svm.SVC(kernel ='linear', C = 1)
svc.fit(X_train, y_train) 

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svc.predict(X_test)

In [41]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))


[[49  1]
 [ 5 38]]
Classification accuracy = 93.54838709677419 %

              precision    recall  f1-score   support

           0       0.91      0.98      0.94        50
           1       0.97      0.88      0.93        43

    accuracy                           0.94        93
   macro avg       0.94      0.93      0.93        93
weighted avg       0.94      0.94      0.94        93



In [42]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8726970147233554

Support Vector Machine with Polynomial Kernel(SVM-P)

In [43]:
from sklearn import svm
svcpoly= svm.SVC(kernel='poly',gamma=3)
svcpoly.fit(X_train, y_train) 

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=3, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svcpoly.predict(X_test)

In [45]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[50  0]
 [12 31]]
Classification accuracy = 87.09677419354838 %

              precision    recall  f1-score   support

           0       0.81      1.00      0.89        50
           1       1.00      0.72      0.84        43

    accuracy                           0.87        93
   macro avg       0.90      0.86      0.87        93
weighted avg       0.90      0.87      0.87        93



In [46]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7624928516630233

Support Vector Machine with Gaussian Kernel(SVM-R)

In [47]:
from sklearn import svm
svcrbf= svm.SVC(kernel='rbf')
svcrbf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svcrbf.predict(X_test)

In [49]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[50  0]
 [ 3 40]]
Classification accuracy = 96.7741935483871 %

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        50
           1       1.00      0.93      0.96        43

    accuracy                           0.97        93
   macro avg       0.97      0.97      0.97        93
weighted avg       0.97      0.97      0.97        93



In [50]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.9367912707947791

Bernoulli Naive Bayes(NB-B)

In [51]:
from sklearn.naive_bayes import BernoulliNB
clfBNB = BernoulliNB()
clfBNB.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [0]:
y_pred=clfBNB.predict(X_test)

In [53]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[50  0]
 [19 24]]
Classification accuracy = 79.56989247311827 %

              precision    recall  f1-score   support

           0       0.72      1.00      0.84        50
           1       1.00      0.56      0.72        43

    accuracy                           0.80        93
   macro avg       0.86      0.78      0.78        93
weighted avg       0.85      0.80      0.78        93



In [54]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.6359630007488933

Multinomial Naive Bayes(NB-M)


In [55]:
from sklearn.naive_bayes import MultinomialNB
clfMNB = MultinomialNB()
clfMNB.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
y_pred=clfMNB.predict(X_test)

In [57]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[48  2]
 [ 5 38]]
Classification accuracy = 92.47311827956989 %

              precision    recall  f1-score   support

           0       0.91      0.96      0.93        50
           1       0.95      0.88      0.92        43

    accuracy                           0.92        93
   macro avg       0.93      0.92      0.92        93
weighted avg       0.93      0.92      0.92        93



In [58]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8496696826108646

Gaussian Naive Bayes(NB-G)

In [59]:
from sklearn.naive_bayes import GaussianNB
clfGNB = GaussianNB()
clfGNB.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred=clfGNB.predict(X_test)

In [61]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[42  8]
 [ 0 43]]
Classification accuracy = 91.39784946236558 %

              precision    recall  f1-score   support

           0       1.00      0.84      0.91        50
           1       0.84      1.00      0.91        43

    accuracy                           0.91        93
   macro avg       0.92      0.92      0.91        93
weighted avg       0.93      0.91      0.91        93



In [62]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.841567165541555