In [0]:
import pandas as pd
import numpy as np
import zipfile

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
zip_ref = zipfile.ZipFile("/content/drive/My Drive/ML Project/YouTube-Spam-Collection-v1.zip", 'r')
zip_ref.extractall()
zip_ref.close()

In [5]:
df=pd.read_csv('/content/Youtube01-Psy.csv')
df.head()

COMMENT_ID  ... CLASS
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU  ...     1
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A  ...     1
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  ...     1
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04  ...     1
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw  ...     1

[5 rows x 5 columns]

In [6]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [7]:
df=df[['CONTENT','CLASS']]
df.head()

CONTENT  CLASS
0  Huh, anyway check out this you[tube] channel: ...      1
1  Hey guys check out my new channel and our firs...      1
2             just for test I have to say murdev.com      1
3   me shaking my sexy ass on my channel enjoy ^_^       1
4            watch?v=vtaRGgvGtWQ   Check this out .      1

In [0]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [11]:
corpus=[]
import re
for i in range(0,df.shape[0]):
    x = re.sub('[^a-zA-Z]', ' ',df['CONTENT'].iloc[i])
    x = x.split()
    x = [ps.stem(word) for word in x if not word in set(stopwords.words('english'))]
    x = ' '.join(x)
    corpus.append(x)
corpus

['huh anyway check tube channel kobyoshi',
 'hey guy check new channel first vid thi IS US the monkey I monkey white shirt pleas leav like comment pleas subscrib',
 'test I say murdev com',
 'shake sexi ass channel enjoy',
 'watch v vtarggvgtwq check',
 'hey check new websit thi site kid stuff kidsmediausa com',
 'subscrib channel',
 'turn mute soon came want check view',
 'you check channel funni video',
 'u check channel tell I next',
 'hey subscrib',
 'onc start read stop If subscrib within one day entir famili die want stay aliv subscrib right',
 'http twitter com gbphotographygb',
 'subscrib like comment',
 'pleas like D http premium easypromosapp com votem',
 'hello Do like game art video scientif experi tutori lyric video much much If pleas check channel subscrib start soon hope abl cover expect you also check got far',
 'I check view',
 'http www ebay com itm sspagenam strk meselx IT amp trksid p l',
 'http ubuntuon com beuutvu zkxk utgpz K',
 'We edm apparel compani dedic brin

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()

In [0]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [14]:
x.shape

(350, 1164)

In [0]:
y = df['CLASS'].values


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3,random_state=35)

LogisticRegression(LR)


In [0]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[54  0]
 [ 5 46]]
Classification accuracy = 95.23809523809523 %

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        54
           1       1.00      0.90      0.95        51

    accuracy                           0.95       105
   macro avg       0.96      0.95      0.95       105
weighted avg       0.96      0.95      0.95       105



In [0]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.9085831991132498

Random Forest(RF)

In [0]:
from sklearn.ensemble import RandomForestClassifier
clfRF = RandomForestClassifier(max_depth=2, random_state=0)
clfRF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred=clfRF.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[53  1]
 [ 5 46]]
Classification accuracy = 94.28571428571428 %

              precision    recall  f1-score   support

           0       0.91      0.98      0.95        54
           1       0.98      0.90      0.94        51

    accuracy                           0.94       105
   macro avg       0.95      0.94      0.94       105
weighted avg       0.95      0.94      0.94       105



In [0]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8879677954888281

DecisionTree(CART)


In [0]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[51  3]
 [ 4 47]]
Classification accuracy = 93.33333333333333 %

              precision    recall  f1-score   support

           0       0.93      0.94      0.94        54
           1       0.94      0.92      0.93        51

    accuracy                           0.93       105
   macro avg       0.93      0.93      0.93       105
weighted avg       0.93      0.93      0.93       105



In [0]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8666426707222403

K-Nearest neighbors(KNN)(3-NN)


In [0]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[54  0]
 [12 39]]
Classification accuracy = 88.57142857142857 %

              precision    recall  f1-score   support

           0       0.82      1.00      0.90        54
           1       1.00      0.76      0.87        51

    accuracy                           0.89       105
   macro avg       0.91      0.88      0.88       105
weighted avg       0.91      0.89      0.88       105



In [0]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7909920664569657

K-Nearest neighbors(KNN)(1-NN)

In [0]:
from sklearn.neighbors import KNeighborsClassifier
neigh1 = KNeighborsClassifier(n_neighbors=1)
neigh1.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh1.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[54  0]
 [11 40]]
Classification accuracy = 89.52380952380953 %

              precision    recall  f1-score   support

           0       0.83      1.00      0.91        54
           1       1.00      0.78      0.88        51

    accuracy                           0.90       105
   macro avg       0.92      0.89      0.89       105
weighted avg       0.91      0.90      0.89       105



In [0]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.807207352795575

K-Nearest neighbors(KNN)(5-NN)

In [0]:
from sklearn.neighbors import KNeighborsClassifier
neigh5 = KNeighborsClassifier(n_neighbors=5)
neigh5.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh5.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[54  0]
 [ 9 42]]
Classification accuracy = 91.42857142857143 %

              precision    recall  f1-score   support

           0       0.86      1.00      0.92        54
           1       1.00      0.82      0.90        51

    accuracy                           0.91       105
   macro avg       0.93      0.91      0.91       105
weighted avg       0.93      0.91      0.91       105



In [0]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8401680504168059

Support Vector Machine with Linear Kernel(SVM-L)

In [0]:
from sklearn import svm
svc = svm.SVC(kernel ='linear', C = 1)
svc.fit(X_train, y_train) 

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svc.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))


[[52  2]
 [ 5 46]]
Classification accuracy = 93.33333333333333 %

              precision    recall  f1-score   support

           0       0.91      0.96      0.94        54
           1       0.96      0.90      0.93        51

    accuracy                           0.93       105
   macro avg       0.94      0.93      0.93       105
weighted avg       0.93      0.93      0.93       105



In [0]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8677642269993321

Support Vector Machine with Polynomial Kernel(SVM-P)

In [0]:
from sklearn import svm
svcpoly= svm.SVC(kernel='poly',gamma=2)
svcpoly.fit(X_train, y_train) 

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=2, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svcpoly.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[54  0]
 [23 28]]
Classification accuracy = 78.0952380952381 %

              precision    recall  f1-score   support

           0       0.70      1.00      0.82        54
           1       1.00      0.55      0.71        51

    accuracy                           0.78       105
   macro avg       0.85      0.77      0.77       105
weighted avg       0.85      0.78      0.77       105



In [0]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.620505227994023

Support Vector Machine with Gaussian Kernel(SVM-R)

In [0]:
from sklearn import svm
svcrbf= svm.SVC(kernel='rbf')
svcrbf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svcrbf.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[52  2]
 [ 5 46]]
Classification accuracy = 93.33333333333333 %

              precision    recall  f1-score   support

           0       0.91      0.96      0.94        54
           1       0.96      0.90      0.93        51

    accuracy                           0.93       105
   macro avg       0.94      0.93      0.93       105
weighted avg       0.93      0.93      0.93       105



In [0]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8677642269993321

Bernoulli Naive Bayes(NB-B)

In [0]:
from sklearn.naive_bayes import BernoulliNB
clfBNB = BernoulliNB()
clfBNB.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [0]:
y_pred=clfBNB.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[54  0]
 [11 40]]
Classification accuracy = 89.52380952380953 %

              precision    recall  f1-score   support

           0       0.83      1.00      0.91        54
           1       1.00      0.78      0.88        51

    accuracy                           0.90       105
   macro avg       0.92      0.89      0.89       105
weighted avg       0.91      0.90      0.89       105



In [0]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.807207352795575

Multinomial Naive Bayes(NB-M)


In [0]:
from sklearn.naive_bayes import MultinomialNB
clfMNB = MultinomialNB()
clfMNB.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
y_pred=clfMNB.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[52  2]
 [ 6 45]]
Classification accuracy = 92.38095238095238 %

              precision    recall  f1-score   support

           0       0.90      0.96      0.93        54
           1       0.96      0.88      0.92        51

    accuracy                           0.92       105
   macro avg       0.93      0.92      0.92       105
weighted avg       0.93      0.92      0.92       105



In [0]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8496461273727873

Gaussian Naive Bayes(NB-G)

In [0]:
from sklearn.naive_bayes import GaussianNB
clfGNB = GaussianNB()
clfGNB.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred=clfGNB.predict(X_test)

In [0]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[48  6]
 [10 41]]
Classification accuracy = 84.76190476190476 %

              precision    recall  f1-score   support

           0       0.83      0.89      0.86        54
           1       0.87      0.80      0.84        51

    accuracy                           0.85       105
   macro avg       0.85      0.85      0.85       105
weighted avg       0.85      0.85      0.85       105



In [0]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.6963594549086247