In [0]:
import pandas as pd
import numpy as np
import zipfile

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
zip_ref = zipfile.ZipFile("/content/drive/My Drive/ML Project/YouTube-Spam-Collection-v1.zip", 'r')
zip_ref.extractall()
zip_ref.close()

In [6]:
df=pd.read_csv('/content/Youtube03-LMFAO.csv')
df.head()

COMMENT_ID  ... CLASS
0  z13uwn2heqndtr5g304ccv5j5kqqzxjadmc0k  ...     0
1  z124jvczaz3dxhnbc04cffk43oiugj25yzo0k  ...     0
2      z13tczjy5xj0vjmu5231unho1ofey5zdk  ...     1
3  z13tzr0hdpnayhqqc04cd3zqqqjkf3ngckk0k  ...     0
4  z12pcvix4zedcjvyb04ccr1r0mr2g5xwyng0k  ...     0

[5 rows x 5 columns]

In [7]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [8]:
df=df[['CONTENT','CLASS']]
df.head()

CONTENT  CLASS
0  <a href="http://www.youtube.com/watch?v=KQ6zr6...      0
1                                   wierd but funny      0
2  Hey guys, I&#39;m a human.<br /><br /><br />Bu...      1
3       Party Rock....lol...who wants to shuffle!!!      0
4                                        Party rock      0

In [0]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [10]:
corpus=[]
import re
for i in range(0,df.shape[0]):
    x = re.sub('[^a-zA-Z]', ' ',df['CONTENT'].iloc[i])
    x = x.split()
    x = [ps.stem(word) for word in x if not word in set(stopwords.words('english'))]
    x = ' '.join(x)
    corpus.append(x)
corpus

['href http www youtub com watch v KQ zr kcpj amp best part',
 'wierd funni',
 'hey guy I human br br br but I want human I want sexi fuck giraff br br br I alreadi money surgeri elong spinal core surgeri chang skin pigment everyth els like post other root dream br br br Im fuck I make music check first song rel nofollow class ot hashtag href http plu googl com giraffebruuh giraffebruuh',
 'parti rock lol want shuffl',
 'parti rock',
 'shuffl',
 'omg',
 'thi song realli fun',
 'awsom br',
 'wow increibl song',
 'I love song much',
 'likee',
 'I miss peopl dress like',
 'last year decent music',
 'best song ever',
 'super nice love musiqu',
 'wowwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
 'parti rock',
 'thumb watch',
 'increidebl',
 'lmfao',
 'superr',
 'llike',
 'yeah let start parti',
 'thi awesom song need year reach mil view tango switch bitch need year fairrrrrrr',
 'nice girl D',
 'I rememb back popular everyon school shuffl crazi',
 'lmfao',
 'super awesom video br',
 'just danc',
 'thi wi

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()

In [12]:
x

array([[0, 0, 0, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [13]:
x.shape

(438, 785)

In [0]:
y = df['CLASS'].values


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3,random_state=35)

LogisticRegression(LR)


In [16]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred = classifier.predict(X_test)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[70  0]
 [ 5 57]]
Classification accuracy = 96.21212121212122 %

              precision    recall  f1-score   support

           0       0.93      1.00      0.97        70
           1       1.00      0.92      0.96        62

    accuracy                           0.96       132
   macro avg       0.97      0.96      0.96       132
weighted avg       0.96      0.96      0.96       132



In [19]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.9263177187817538

Random Forest(RF)

In [20]:
from sklearn.ensemble import RandomForestClassifier
clfRF = RandomForestClassifier(max_depth=2, random_state=0)
clfRF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred=clfRF.predict(X_test)

In [22]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[42 28]
 [ 1 61]]
Classification accuracy = 78.03030303030303 %

              precision    recall  f1-score   support

           0       0.98      0.60      0.74        70
           1       0.69      0.98      0.81        62

    accuracy                           0.78       132
   macro avg       0.83      0.79      0.78       132
weighted avg       0.84      0.78      0.77       132



In [23]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.621773938407603

DecisionTree(CART)


In [24]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [0]:
y_pred = classifier.predict(X_test)

In [26]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[68  2]
 [ 2 60]]
Classification accuracy = 96.96969696969697 %

              precision    recall  f1-score   support

           0       0.97      0.97      0.97        70
           1       0.97      0.97      0.97        62

    accuracy                           0.97       132
   macro avg       0.97      0.97      0.97       132
weighted avg       0.97      0.97      0.97       132



In [27]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.9391705069124424

K-Nearest neighbors(KNN)(3-NN)


In [28]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh.predict(X_test)

In [30]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[69  1]
 [ 9 53]]
Classification accuracy = 92.42424242424242 %

              precision    recall  f1-score   support

           0       0.88      0.99      0.93        70
           1       0.98      0.85      0.91        62

    accuracy                           0.92       132
   macro avg       0.93      0.92      0.92       132
weighted avg       0.93      0.92      0.92       132



In [31]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.853229344957784

K-Nearest neighbors(KNN)(1-NN)

In [32]:
from sklearn.neighbors import KNeighborsClassifier
neigh1 = KNeighborsClassifier(n_neighbors=1)
neigh1.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh1.predict(X_test)

In [34]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[68  2]
 [10 52]]
Classification accuracy = 90.9090909090909 %

              precision    recall  f1-score   support

           0       0.87      0.97      0.92        70
           1       0.96      0.84      0.90        62

    accuracy                           0.91       132
   macro avg       0.92      0.91      0.91       132
weighted avg       0.91      0.91      0.91       132



In [35]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.822355914712601

K-Nearest neighbors(KNN)(5-NN)

In [36]:
from sklearn.neighbors import KNeighborsClassifier
neigh5 = KNeighborsClassifier(n_neighbors=5)
neigh5.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred = neigh5.predict(X_test)

In [38]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[70  0]
 [ 7 55]]
Classification accuracy = 94.6969696969697 %

              precision    recall  f1-score   support

           0       0.91      1.00      0.95        70
           1       1.00      0.89      0.94        62

    accuracy                           0.95       132
   macro avg       0.95      0.94      0.95       132
weighted avg       0.95      0.95      0.95       132



In [39]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8980265101338746

Support Vector Machine with Linear Kernel(SVM-L)

In [40]:
from sklearn import svm
svc = svm.SVC(kernel ='linear', C = 1)
svc.fit(X_train, y_train) 

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svc.predict(X_test)

In [42]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))


[[69  1]
 [ 5 57]]
Classification accuracy = 95.45454545454545 %

              precision    recall  f1-score   support

           0       0.93      0.99      0.96        70
           1       0.98      0.92      0.95        62

    accuracy                           0.95       132
   macro avg       0.96      0.95      0.95       132
weighted avg       0.96      0.95      0.95       132



In [43]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.9101160174009973

Support Vector Machine with Polynomial Kernel(SVM-P)

In [44]:
from sklearn import svm
svcpoly= svm.SVC(kernel='poly',gamma=2)
svcpoly.fit(X_train, y_train) 

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=2, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svcpoly.predict(X_test)

In [46]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[69  1]
 [ 9 53]]
Classification accuracy = 92.42424242424242 %

              precision    recall  f1-score   support

           0       0.88      0.99      0.93        70
           1       0.98      0.85      0.91        62

    accuracy                           0.92       132
   macro avg       0.93      0.92      0.92       132
weighted avg       0.93      0.92      0.92       132



In [47]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.853229344957784

Support Vector Machine with Gaussian Kernel(SVM-R)

In [48]:
from sklearn import svm
svcrbf= svm.SVC(kernel='rbf')
svcrbf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = svcrbf.predict(X_test)

In [50]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[60 10]
 [ 3 59]]
Classification accuracy = 90.15151515151516 %

              precision    recall  f1-score   support

           0       0.95      0.86      0.90        70
           1       0.86      0.95      0.90        62

    accuracy                           0.90       132
   macro avg       0.90      0.90      0.90       132
weighted avg       0.91      0.90      0.90       132



In [51]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8081043259010032

Bernoulli Naive Bayes(NB-B)

In [52]:
from sklearn.naive_bayes import BernoulliNB
clfBNB = BernoulliNB()
clfBNB.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [0]:
y_pred=clfBNB.predict(X_test)

In [54]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[69  1]
 [ 5 57]]
Classification accuracy = 95.45454545454545 %

              precision    recall  f1-score   support

           0       0.93      0.99      0.96        70
           1       0.98      0.92      0.95        62

    accuracy                           0.95       132
   macro avg       0.96      0.95      0.95       132
weighted avg       0.96      0.95      0.95       132



In [55]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.9101160174009973

Multinomial Naive Bayes(NB-M)


In [56]:
from sklearn.naive_bayes import MultinomialNB
clfMNB = MultinomialNB()
clfMNB.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
y_pred=clfMNB.predict(X_test)

In [58]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[63  7]
 [ 4 58]]
Classification accuracy = 91.66666666666666 %

              precision    recall  f1-score   support

           0       0.94      0.90      0.92        70
           1       0.89      0.94      0.91        62

    accuracy                           0.92       132
   macro avg       0.92      0.92      0.92       132
weighted avg       0.92      0.92      0.92       132



In [59]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.8340437942793514

Gaussian Naive Bayes(NB-G)

In [60]:
from sklearn.naive_bayes import GaussianNB
clfGNB = GaussianNB()
clfGNB.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred=clfGNB.predict(X_test)

In [62]:
print(confusion_matrix(y_test,y_pred))
print('Classification accuracy =',accuracy_score(y_test,y_pred)*100,'%\n')
print(classification_report(y_test,y_pred))

[[58 12]
 [ 4 58]]
Classification accuracy = 87.87878787878788 %

              precision    recall  f1-score   support

           0       0.94      0.83      0.88        70
           1       0.83      0.94      0.88        62

    accuracy                           0.88       132
   macro avg       0.88      0.88      0.88       132
weighted avg       0.89      0.88      0.88       132



In [63]:
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

0.7640552995391705